export const GET_PRODUCT_SUCCESS="GET_PRODUCT_SUCCESS"
export const GET_PRODUCT_LOADING="GET_PRODUCT_LOADING"
export const GET_PRODUCT_ERROR="GET_PRODUCT_ERROR"

export const GET_PRODUCTDETAIL_SUCCESS="GET_PRODUCTDETAIL_SUCCESS"
export const GET_PRODUCTDETAIL_LOADING="GET_PRODUCTDETAIL_LOADING"
export const GET_PRODUCTDETAIL_ERROR="GET_PRODUCTDETAIL_ERROR"